name = "toolbox"
uuid = "7781f4b9-0ba3-4b3e-a982-d971b817e3a7"
version = "0.1.0"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[compat]
DelimitedFiles = "1.9.1"
